version: '3'

services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'

  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # Don't touch this one
      - /app/node_modules
      # Everytime we try to acces /app, it will be redirected to ./server
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:      
      - /app/node_modules      
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:      
      - /app/node_modules      
      - ./worker:/app

  ## docker-compose up --build